"""
retriever.py — Document retrieval using ChromaDB vector database.


WHAT CHANGED FROM FAISS VERSION:
─────────────────────────────────────────────────────────────────────────────
BEFORE:
    Storage  : chunks.pkl + doc_index.faiss + uploaded_docs.pkl + doc_metadata.pkl
    Dedup    : manual MD5 hashing
    Delete   : impossible without wiping entire index
    Filter   : post-retrieval Python loop
    Persist  : manual _save_index_and_chunks() calls everywhere

AFTER:
    Storage  : single chroma_db/ folder (auto-managed)
    Dedup    : ChromaDB document IDs (duplicate ID = skip)
    Delete   : collection.delete(where={"source": filename})
    Filter   : inside vector search via where= clause
    Persist  : automatic — every add/delete is instantly saved
─────────────────────────────────────────────────────────────────────────────
"""

import os
import io
import re
import hashlib

import numpy as np
import chromadb
from chromadb.config import Settings
from sentence_transformers import SentenceTransformer, CrossEncoder
from PyPDF2 import PdfReader
from doc_analyzer import analyze_document
from logger import log_upload, log_delete

# ── Constants ──────────────────────────────────────────────────────────────────
CHUNK_SIZE    = 5      # sentences per chunk
CHUNK_OVERLAP = 2      # overlap sentences between chunks
TOP_K_FETCH   = 12     # candidates fetched from ChromaDB before reranking

# ─────────────────────────────────────────────────────────────────────────────
# CHROMA DB PATH
#
# ChromaDB stores everything in a local folder called chroma_db/.
# This folder is created automatically on first run.
# It replaces ALL of these files:
#   chunks.pkl, doc_index.faiss, uploaded_docs.pkl, doc_metadata.pkl
#
# PersistentClient means every add/delete is instantly written to disk.
# You never need to call a save function manually.
# ─────────────────────────────────────────────────────────────────────────────
CHROMA_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "chroma_db")

# ─────────────────────────────────────────────────────────────────────────────
# DOC METADATA FILE
#
# We keep ONE small pickle file for document summaries only.
# ChromaDB stores chunks + embeddings. Summaries are separate metadata
# generated by the LLM and stored here.
# Everything else (chunks, vectors, doc list) lives in ChromaDB.
# ─────────────────────────────────────────────────────────────────────────────
DOC_META_FILE = "doc_metadata.pkl"
import pickle

# ── Models ─────────────────────────────────────────────────────────────────────
# ─────────────────────────────────────────────────────────────────────────────
# WHY WE PASS OUR OWN EMBEDDINGS TO CHROMADB:
#
# ChromaDB can compute embeddings internally, but we pass them ourselves.
# Reason: we want to use the SAME all-MiniLM-L6-v2 model for both:
#   1. Indexing chunks (here in retriever.py)
#   2. The cross-encoder reranker (ms-marco was trained alongside MiniLM)
#
# If ChromaDB used a different embedding model internally, the vectors
# wouldn't be compatible with our reranker's expectations.
# ─────────────────────────────────────────────────────────────────────────────
embed_model = SentenceTransformer("all-MiniLM-L6-v2")
reranker    = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")

# ─────────────────────────────────────────────────────────────────────────────
# CHROMADB CLIENT + COLLECTION SETUP
#
# client     : the database connection, points to chroma_db/ folder
# collection : like a SQL table — holds all our chunks
#
# get_or_create_collection:
#   - If "documents" collection exists → load it (with all existing chunks)
#   - If not → create a fresh empty one
#   This means the app works correctly on both first run and subsequent runs.
#
# metadata={"hnsw:space": "cosine"}:
#   ChromaDB uses HNSW (Hierarchical Navigable Small World) graph internally
#   for approximate nearest neighbor search — faster than FAISS flat index
#   for large collections. cosine similarity is better for text than L2
#   because it's length-invariant (a long chunk and short chunk about the
#   same topic will still score similarly).
# ─────────────────────────────────────────────────────────────────────────────
client = chromadb.PersistentClient(
    path=CHROMA_PATH,
    settings=Settings(anonymized_telemetry=False)   # disable usage tracking
)

collection = client.get_or_create_collection(
    name="documents",
    metadata={"hnsw:space": "cosine"}
)


# ── Metadata helpers ───────────────────────────────────────────────────────────

def _load_metadata():
    if os.path.exists(DOC_META_FILE):
        with open(DOC_META_FILE, "rb") as f:
            return pickle.load(f)
    return {}

def _save_metadata(metadata):
    with open(DOC_META_FILE, "wb") as f:
        pickle.dump(metadata, f)


# ─────────────────────────────────────────────────────────────────────────────
# CHUNK ID GENERATION
#
# BEFORE (FAISS):
#   Chunks had integer IDs (0, 1, 2...) stored in chunks.pkl.
#   Deduplication required computing MD5 hash of each chunk text
#   and manually checking against a set.
#
# NOW (ChromaDB):
#   Every chunk has a STRING ID like "Database_Management.pdf_chunk_007"
#   ChromaDB enforces uniqueness by ID automatically.
#   If you try to add a chunk with an existing ID, ChromaDB skips it.
#   No manual MD5 hashing needed — the ID IS the deduplication key.
#
# We build the ID from: filename (cleaned) + chunk index
# This means re-uploading the same file produces the same IDs → no duplicates.
# ─────────────────────────────────────────────────────────────────────────────

def _make_chunk_id(source, chunk_index):
    """
    Create a stable, unique chunk ID from filename + index.
    Same file + same index = same ID → ChromaDB skips duplicates automatically.
    """
    # Clean filename: remove special chars, keep alphanumeric + underscore
    clean_name = re.sub(r"[^a-zA-Z0-9_]", "_", source)
    return f"{clean_name}_chunk_{chunk_index:04d}"


# ── PDF Cleaning ───────────────────────────────────────────────────────────────
# ─────────────────────────────────────────────────────────────────────────────
# WHY THIS EXISTS (recap):
#   PyPDF2 extracts styled PDF headings as per-word line breaks:
#   "Database \nManagement \nSystems" instead of "Database Management Systems"
#   This garbles embeddings → wrong chunks retrieved → hallucinated answers.
#   This cleaner was the fix that brought rerank scores from -9.8 to +8.4.
# ─────────────────────────────────────────────────────────────────────────────

def _clean_pdf_text(raw_pages):
    """Join PDF pages into clean prose, collapsing PyPDF2 extraction artifacts."""
    cleaned = []
    for page in raw_pages:
        if not page:
            continue
        page = re.sub(r'^\s*\d+\s*$', '', page, flags=re.MULTILINE)  # page numbers
        page = re.sub(r'-\n', '', page)                                # hyphen breaks
        page = re.sub(r'\n(?=[a-z])', ' ', page)                      # lowercase continuation
        page = re.sub(r'\n(?=\S{1,3}\s)', ' ', page)                  # short next word
        page = re.sub(r'(?<![.!?])\n(?!\n)', ' ', page)               # mid-paragraph break
        page = re.sub(r' {2,}', ' ', page)                            # multiple spaces
        page = page.strip()
        if page:
            cleaned.append(page)
    return "\n\n".join(cleaned)


# ── Sentence splitting + Chunking ──────────────────────────────────────────────
# ─────────────────────────────────────────────────────────────────────────────
# WHY SENTENCE-AWARE CHUNKING (recap):
#   Old: split every 300 words → mid-sentence cuts → broken context
#   New: split on sentence boundaries → 5-sentence windows → 2-sentence overlap
#   Overlap ensures concepts straddling a boundary appear in BOTH chunks.
# ─────────────────────────────────────────────────────────────────────────────

def _split_into_sentences(text):
    raw = re.split(r'(?<=[.!?])\s+(?=[A-Z])', text.strip())
    sentences = []
    for fragment in raw:
        for part in re.split(r'\n{2,}', fragment):
            part = part.strip()
            if len(part) > 20:
                sentences.append(part)
    return sentences


def chunk_text(text, chunk_size=CHUNK_SIZE, overlap=CHUNK_OVERLAP):
    """Sentence-aware chunking with overlap."""
    sentences = _split_into_sentences(text)
    if not sentences:
        return []
    if len(sentences) <= chunk_size:
        return [" ".join(sentences)]
    step = max(1, chunk_size - overlap)
    out, i = [], 0
    while i < len(sentences):
        out.append(" ".join(sentences[i: i + chunk_size]))
        i += step
    return out


# ── Indexing ───────────────────────────────────────────────────────────────────

def index_text_document(text, source):
    """
    Index a text document into ChromaDB.

    HOW THIS WORKS:
    ─────────────────────────────────────────────────────────────────────────
    1. Chunk the text into sentence-aware windows
    2. Generate embeddings for all chunks in one batch
    3. Build IDs, texts, metadatas lists
    4. Call collection.add() — ChromaDB handles:
         - storing the vectors
         - storing the raw text
         - storing the metadata
         - persisting to disk automatically
         - skipping any chunk whose ID already exists (deduplication)

    BEFORE (FAISS version):
        Had to manually:
        - compute MD5 hashes to detect duplicates
        - call index.add(embeddings)
        - append to chunks list
        - call _save_index_and_chunks() to write pkl files

    NOW:
        collection.add() does all of that in one call.
    ─────────────────────────────────────────────────────────────────────────
    """
    text = text.strip()
    if not text:
        return 0

    text_chunks = chunk_text(text)
    if not text_chunks:
        return 0

    # ── Check which chunk IDs already exist ───────────────────────────────────
    # ChromaDB will raise an error if you try to add a duplicate ID.
    # So we check first and only add truly new chunks.
    new_texts     = []
    new_ids       = []
    new_metadatas = []

    # Get count of existing chunks for this source to build correct indices
    existing = collection.get(where={"source": source})
    existing_ids = set(existing["ids"]) if existing["ids"] else set()

    for i, ch in enumerate(text_chunks):
        chunk_id = _make_chunk_id(source, i)
        if chunk_id in existing_ids:
            continue    # already indexed — skip (deduplication)
        new_texts.append(ch)
        new_ids.append(chunk_id)
        new_metadatas.append({"source": source})

    if not new_texts:
        return 0

    # ── Compute embeddings ────────────────────────────────────────────────────
    # We compute embeddings ourselves (not ChromaDB's built-in embedder)
    # so we control exactly which model is used.
    embeddings = embed_model.encode(new_texts, show_progress_bar=False)
    embeddings = [e.tolist() for e in embeddings]   # ChromaDB needs Python lists

    # ── Add to ChromaDB ───────────────────────────────────────────────────────
    # One call replaces: index.add() + chunks.extend() + _save_index_and_chunks()
    collection.add(
        documents=new_texts,
        embeddings=embeddings,
        ids=new_ids,
        metadatas=new_metadatas,
    )

    return len(new_texts)


# ── Retrieval ──────────────────────────────────────────────────────────────────

def retrieve_context(question, k=4, selected_doc=None):
    """
    Retrieve relevant chunks using ChromaDB + cross-encoder reranking.

    PIPELINE (same two-stage logic as before, cleaner implementation):
    ─────────────────────────────────────────────────────────────────────────
    Stage 1 — ChromaDB vector search (was: FAISS)
        - Embeds the question
        - Searches the collection
        - Filters by source document INSIDE the search (was: post-retrieval loop)
        - Returns TOP_K_FETCH=12 candidates

    Stage 2 — Cross-encoder reranking (unchanged)
        - Takes (question, chunk) pairs
        - Scores each pair for true relevance
        - Returns top k sorted by rerank score

    KEY IMPROVEMENT over FAISS version:
        The where= filter in ChromaDB runs INSIDE the vector search.
        FAISS fetched ALL documents then filtered in Python.
        ChromaDB only searches chunks from the selected document.
        Faster and more precise for multi-document collections.
    ─────────────────────────────────────────────────────────────────────────
    """
    if collection.count() == 0:
        return []

    # Embed the question
    question_emb = embed_model.encode([question], show_progress_bar=False)
    question_emb = [question_emb[0].tolist()]

    # ── Stage 1: ChromaDB vector search ──────────────────────────────────────
    query_kwargs = {
        "query_embeddings": question_emb,
        "n_results": min(TOP_K_FETCH, collection.count()),
        "include": ["documents", "metadatas", "distances"],
    }

    # Filter by document INSIDE the search — cleaner than post-retrieval filtering
    if selected_doc:
        query_kwargs["where"] = {"source": selected_doc}

    results = collection.query(**query_kwargs)

    # Unpack ChromaDB results
    # results["documents"][0] = list of chunk texts
    # results["distances"][0] = list of cosine distances (lower = more similar)
    # results["metadatas"][0] = list of metadata dicts
    docs      = results["documents"][0]
    distances = results["distances"][0]
    metas     = results["metadatas"][0]

    if not docs:
        return []

    candidates = [
        {
            "text":   doc,
            "source": meta.get("source", ""),
            "score":  float(dist),       # cosine distance (lower = better)
        }
        for doc, dist, meta in zip(docs, distances, metas)
    ]

    # ── Stage 2: Cross-encoder reranking (unchanged logic) ───────────────────
    pairs         = [(question, c["text"]) for c in candidates]
    rerank_scores = reranker.predict(pairs)

    for c, rs in zip(candidates, rerank_scores):
        c["rerank_score"] = float(rs)

    candidates.sort(key=lambda x: x["rerank_score"], reverse=True)
    return candidates[:k]


# ── Document management ────────────────────────────────────────────────────────

def get_all_documents():
    """
    Return list of all indexed document names.

    BEFORE: loaded uploaded_docs.pkl manually
    NOW:    query ChromaDB metadata directly — single source of truth
    """
    if collection.count() == 0:
        return []
    all_metas = collection.get(include=["metadatas"])["metadatas"]
    return sorted(set(m["source"] for m in all_metas if m.get("source")))


def delete_document(filename):
    """
    DELETE a specific document from the index.

    THIS WAS IMPOSSIBLE WITH FAISS.
    With FAISS, deleting one document meant:
        1. Delete all pkl files
        2. Re-index every other document from scratch

    With ChromaDB:
        collection.delete(where={"source": filename})
        One line. Done. Everything else untouched.

    Also removes the document summary from metadata.
    """
    # Delete all chunks belonging to this document
    collection.delete(where={"source": filename})

    # Log the deletion
    log_delete(filename)

    # Remove from summary metadata
    metadata = _load_metadata()
    if filename in metadata:
        del metadata[filename]
        _save_metadata(metadata)

    return True


def add_new_document(file_bytes, filename):
    """
    Ingest a new TXT or PDF document.

    Flow:
    1. Extract text (PDF: _clean_pdf_text, TXT: decode UTF-8)
    2. Index into ChromaDB via index_text_document()
    3. Generate and store LLM summary in doc_metadata.pkl

    Returns True if new chunks were added, False if already indexed.
    """
    ext  = os.path.splitext(filename)[1].lower()
    text = ""

    if ext == ".pdf":
        try:
            reader    = PdfReader(io.BytesIO(file_bytes))
            raw_pages = [p.extract_text() for p in reader.pages if p.extract_text()]
            text      = _clean_pdf_text(raw_pages)
        except Exception as e:
            print(f"Failed to read PDF {filename}: {e}")
            return False
    else:
        try:
            text = file_bytes.decode("utf-8", errors="ignore")
        except Exception as e:
            print(f"Failed to decode {filename}: {e}")
            return False

    if not text.strip():
        print(f"No text found in {filename}")
        return False

    # Index — ChromaDB handles dedup via chunk IDs
    num_chunks = index_text_document(text, source=filename)
    if num_chunks == 0:
        return False    # already fully indexed

    # Log the upload
    log_upload(filename, num_chunks)

    # Generate summary (best-effort)
    try:
        summary  = analyze_document(text[:3000])
        metadata = _load_metadata()
        metadata[filename] = {"summary": summary}
        _save_metadata(metadata)
    except Exception as e:
        print(f"Summary failed for {filename}: {e}")

    return True